name: Create and upload release assets

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Determine tag name
        id: tagName
        run: echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"

      - name: Update manifest version
        uses: jossef/action-set-json-field@v2.2
        with:
          file: public/manifest.json
          field: Version
          value: ${{ steps.tagName.outputs.tag }}.${{ github.run_number }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Streamdeck Bundle
        run: npm run bundle

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./de.perdoctus.streamdeck.homeassistant.streamDeckPlugin
